Repository revanced/revanced-patches, pull requests merged in 2022-07, with the labels that each got.

#115 feat: `swipe-controls` patch
  src/main/kotlin/app/revanced/extensions/Extensions.kt
  src/main/kotlin/app/revanced/patches/youtube/interaction/fenster/annotation/FensterCompatibility.kt
  src/main/kotlin/app/revanced/patches/youtube/interaction/fenster/fingerprints/UpdatePlayerTypeFingerprint.kt
  src/main/kotlin/app/revanced/patches/youtube/interaction/fenster/patch/FensterPatch.kt
Labels: patch

#130 feat: implement `wide-searchbar` Patch
  src/main/kotlin/app/revanced/patches/youtube/layout/widesearchbar/annotations/WideSearchbarCompatibility.kt
  src/main/kotlin/app/revanced/patches/youtube/layout/widesearchbar/fingerprints/methodone/WideSearchbarOneFingerprint.kt
  src/main/kotlin/app/revanced/patches/youtube/layout/widesearchbar/fingerprints/methodone/WideSearchbarOneParentFingerprint.kt
  src/main/kotlin/app/revanced/patches/youtube/layout/widesearchbar/fingerprints/methodtwo/WideSearchbarTwoFingerprint.kt
  src/main/kotlin/app/revanced/patches/youtube/layout/widesearchbar/fingerprints/methodtwo/WideSearchbarTwoParentFingerprint.kt
  src/main/kotlin/app/revanced/patches/youtube/layout/widesearchbar/patch/WideSearchbarPatch.kt
Labels: patch

#133 docs: auto generate list of patches in `README.md`
  .releaserc
  README.md
  build.gradle.kts
  src/main/kotlin/app/revanced/meta/ReadmeGenerator.kt
Labels: documentation, enhancement

#106 feat: `autorepeat-by-default` patch
  build.gradle.kts
  src/main/kotlin/app/revanced/patches/youtube/layout/autorepeat/annotations/AutoRepeatCompatibility.kt
  src/main/kotlin/app/revanced/patches/youtube/layout/autorepeat/fingerprints/AutoRepeatFingerprint.kt
  src/main/kotlin/app/revanced/patches/youtube/layout/autorepeat/fingerprints/AutoRepeatParentFingerprint.kt
  src/main/kotlin/app/revanced/patches/youtube/layout/autorepeat/patch/AutoRepeatPatch.kt
Labels: patch

#138 docs: templated readme
  README-template.md
  build.gradle.kts
  src/main/kotlin/app/revanced/meta/readme/Generator.kt
  src/main/kotlin/app/revanced/meta/readme/Template.kt
Labels: documentation

#172 feat: `music-video-ads`
  src/main/kotlin/app/revanced/patches/music/ad/video/annotations/MusicVideoAdsCompatibility.kt
  src/main/kotlin/app/revanced/patches/music/ad/video/fingerprints/ShowMusicVideoAdsConstructorFingerprint.kt
  src/main/kotlin/app/revanced/patches/music/ad/video/fingerprints/ShowMusicVideoAdsFingerprint.kt
  src/main/kotlin/app/revanced/patches/music/ad/video/patch/MusicVideoAdsPatch.kt
Labels: change-required

#175 feat: return youtube dislikes
  src/main/kotlin/app/revanced/patches/youtube/layout/returnyoutubedislikes/annotations/RYDCompatibility.kt
  src/main/kotlin/app/revanced/patches/youtube/layout/returnyoutubedislikes/fingerprints/DislikeFingerprint.kt
  src/main/kotlin/app/revanced/patches/youtube/layout/returnyoutubedislikes/fingerprints/LikeFingerprint.kt
  src/main/kotlin/app/revanced/patches/youtube/layout/returnyoutubedislikes/fingerprints/RemoveLikeFingerprint.kt
  src/main/kotlin/app/revanced/patches/youtube/layout/returnyoutubedislikes/fingerprints/TextComponentSpecParentFingerprint.kt
  src/main/kotlin/app/revanced/patches/youtube/layout/returnyoutubedislikes/patch/RYDPatch.kt
  src/main/kotlin/app/revanced/patches/youtube/misc/videoid/annotation/VideoIdCompatibility.kt
  src/main/kotlin/app/revanced/patches/youtube/misc/videoid/fingerprint/VideoIdFingerprint.kt
  src/main/kotlin/app/revanced/patches/youtube/misc/videoid/patch/VideoIdPatch.kt
Labels: feature-request

#157 feat: `force-vp9-codec` patch
  src/main/kotlin/app/revanced/patches/youtube/misc/forcevp9/annotations/ForceVP9Compatibility.kt
  src/main/kotlin/app/revanced/patches/youtube/misc/forcevp9/fingerprints/ForceVP9CodecFingerprint.kt
  src/main/kotlin/app/revanced/patches/youtube/misc/forcevp9/fingerprints/ForceVP9CodecFingerprintTwo.kt
  src/main/kotlin/app/revanced/patches/youtube/misc/forcevp9/fingerprints/ForceVP9ParentFingerprint.kt
  src/main/kotlin/app/revanced/patches/youtube/misc/forcevp9/fingerprints/ReplaceDeviceInfoFingerprint.kt
  src/main/kotlin/app/revanced/patches/youtube/misc/forcevp9/fingerprints/ReplaceDeviceInfoParentFingerprint.kt
  src/main/kotlin/app/revanced/patches/youtube/misc/forcevp9/patch/ForceVP9CodecPatch.kt
Labels: feature-request

#101 feat: `sponsorblock` patch
  src/main/kotlin/app/revanced/patches/youtube/ad/general/resource/patch/GeneralResourceAdsPatch.kt
  src/main/kotlin/app/revanced/patches/youtube/layout/sponsorblock/annotations/SponsorBlockCompatibility.kt
  src/main/kotlin/app/revanced/patches/youtube/layout/sponsorblock/bytecode/fingerprints/AppendTimeFingerprint.kt
  src/main/kotlin/app/revanced/patches/youtube/layout/sponsorblock/bytecode/fingerprints/CreateVideoPlayerSeekbarFingerprint.kt
  src/main/kotlin/app/revanced/patches/youtube/layout/sponsorblock/bytecode/fingerprints/NextGenWatchLayoutFingerprint.kt
  src/main/kotlin/app/revanced/patches/youtube/layout/sponsorblock/bytecode/fingerprints/PlayerControllerSetTimeReferenceFingerprint.kt
  src/main/kotlin/app/revanced/patches/youtube/layout/sponsorblock/bytecode/fingerprints/PlayerInitFingerprint.kt
  src/main/kotlin/app/revanced/patches/youtube/layout/sponsorblock/bytecode/fingerprints/PlayerOverlaysLayoutInitFingerprint.kt
  src/main/kotlin/app/revanced/patches/youtube/layout/sponsorblock/bytecode/fingerprints/RectangleFieldInvalidatorFingerprint.kt
  src/main/kotlin/app/revanced/patches/youtube/layout/sponsorblock/bytecode/fingerprints/SeekFingerprint.kt
  src/main/kotlin/app/revanced/patches/youtube/layout/sponsorblock/bytecode/fingerprints/ShowPlayerControlsFingerprint.kt
  src/main/kotlin/app/revanced/patches/youtube/layout/sponsorblock/bytecode/fingerprints/VideoLengthFingerprint.kt
  src/main/kotlin/app/revanced/patches/youtube/layout/sponsorblock/bytecode/fingerprints/VideoTimeFingerprint.kt
  src/main/kotlin/app/revanced/patches/youtube/layout/sponsorblock/bytecode/patch/SponsorBlockBytecodePatch.kt
  src/main/kotlin/app/revanced/patches/youtube/layout/sponsorblock/resource/patch/SponsorBlockResourcePatch.kt
  src/main/kotlin/app/revanced/patches/youtube/misc/videoid/patch/VideoIdPatch.kt
  src/main/resources/sponsorblock/drawable/ic_sb_adjust.xml
  src/main/resources/sponsorblock/drawable/ic_sb_compare.xml
  src/main/resources/sponsorblock/drawable/ic_sb_edit.xml
  src/main/resources/sponsorblock/drawable/ic_sb_logo.xml
  src/main/resources/sponsorblock/drawable/ic_sb_publish.xml
  src/main/resources/sponsorblock/drawable/ic_sb_voting.xml
  src/main/resources/sponsorblock/host/layout/youtube_controls_layout.xml
  src/main/resources/sponsorblock/layout/inline_sponsor_overlay.xml
  src/main/resources/sponsorblock/layout/new_segment.xml
  src/main/resources/sponsorblock/layout/skip_sponsor_button.xml
  src/main/resources/sponsorblock/values/strings.xml
Labels: feature-request

#195 feat: `hide-get-premium` patch
  src/main/kotlin/app/revanced/patches/music/layout/premium/annotations/HideGetPremiumCompatibility.kt
  src/main/kotlin/app/revanced/patches/music/layout/premium/fingerprints/HideGetPremiumFingerprint.kt
  src/main/kotlin/app/revanced/patches/music/layout/premium/fingerprints/HideGetPremiumParentFingerprint.kt
  src/main/kotlin/app/revanced/patches/music/layout/premium/patch/HideGetPremiumPatch.kt
Labels: feature-request

#224 fix: make `hide-shorts-button` fingerprint more future-proof
  src/main/kotlin/app/revanced/patches/youtube/layout/shorts/button/annotations/ShortsButtonCompatibility.kt
  src/main/kotlin/app/revanced/patches/youtube/layout/shorts/button/fingerprints/PivotBarButtonsViewFingerprint.kt
  src/main/kotlin/app/revanced/patches/youtube/layout/shorts/button/patch/ShortsButtonRemoverPatch.kt
Labels: wip, testing-needed

#225 fix: bump youtube version to 17.28.34
  src/main/kotlin/app/revanced/patches/youtube/ad/general/annotation/GeneralAdsCompatibility.kt
  src/main/kotlin/app/revanced/patches/youtube/ad/infocardsuggestions/annotations/HideInfocardSuggestionsCompatibility.kt
  src/main/kotlin/app/revanced/patches/youtube/ad/video/annotations/VideoAdsCompatibility.kt
  src/main/kotlin/app/revanced/patches/youtube/interaction/seekbar/annotation/SeekbarTappingCompatibility.kt
  src/main/kotlin/app/revanced/patches/youtube/interaction/swipecontrols/annotation/SwipeControlsCompatibility.kt
  src/main/kotlin/app/revanced/patches/youtube/layout/amoled/annotations/AmoledCompatibility.kt
  src/main/kotlin/app/revanced/patches/youtube/layout/autoplaybutton/annotations/AutoplayButtonCompatibility.kt
  src/main/kotlin/app/revanced/patches/youtube/layout/createbutton/annotations/CreateButtonCompatibility.kt
  src/main/kotlin/app/revanced/patches/youtube/layout/fullscreenpanels/annotations/FullscreenPanelsCompatibility.kt
  src/main/kotlin/app/revanced/patches/youtube/layout/minimizedplayback/annotations/MinimizedPlaybackCompatibility.kt
  src/main/kotlin/app/revanced/patches/youtube/layout/oldqualitylayout/annotations/OldQualityLayoutCompatibility.kt
  src/main/kotlin/app/revanced/patches/youtube/layout/reels/annotations/HideReelsCompatibility.kt
  src/main/kotlin/app/revanced/patches/youtube/layout/returnyoutubedislike/annotations/ReturnYouTubeDislikeCompatibility.kt
  src/main/kotlin/app/revanced/patches/youtube/layout/sponsorblock/annotations/SponsorBlockCompatibility.kt
  src/main/kotlin/app/revanced/patches/youtube/layout/watermark/annotations/HideWaterwarkCompatibility.kt
  src/main/kotlin/app/revanced/patches/youtube/layout/widesearchbar/annotations/WideSearchbarCompatibility.kt
  src/main/kotlin/app/revanced/patches/youtube/misc/autorepeat/annotations/AutoRepeatCompatibility.kt
  src/main/kotlin/app/revanced/patches/youtube/misc/customplaybackspeed/annotations/CustomPlaybackSpeedCompatibility.kt
  src/main/kotlin/app/revanced/patches/youtube/misc/forcevp9/annotations/ForceVP9Compatibility.kt
  src/main/kotlin/app/revanced/patches/youtube/misc/hdrbrightness/annotations/HDRBrightnessCompatibility.kt
  src/main/kotlin/app/revanced/patches/youtube/misc/integrations/annotations/IntegrationsCompatibility.kt
  src/main/kotlin/app/revanced/patches/youtube/misc/manifest/annotations/FixLocaleConfigErrorCompatibility.kt
  src/main/kotlin/app/revanced/patches/youtube/misc/microg/annotations/MicroGPatchCompatibility.kt
  src/main/kotlin/app/revanced/patches/youtube/misc/playeroverlay/annotation/PlayerOverlaysHookCompatibility.kt
  src/main/kotlin/app/revanced/patches/youtube/misc/playertype/annotation/PlayerTypeHookCompatibility.kt
  src/main/kotlin/app/revanced/patches/youtube/misc/videoid/annotation/VideoIdCompatibility.kt
Labels: change-required

#141 feat: `default-video-quality` patch
  CHANGELOG.md
  README.md
  gradle.properties
  src/main/kotlin/app/revanced/patches/youtube/misc/quality/annotations/DefaultVideoQualityCompatibility.kt
  src/main/kotlin/app/revanced/patches/youtube/misc/quality/fingerprints/VideoQualityReferenceFingerprint.kt
  src/main/kotlin/app/revanced/patches/youtube/misc/quality/fingerprints/VideoQualitySetterFingerprint.kt
  src/main/kotlin/app/revanced/patches/youtube/misc/quality/fingerprints/VideoUserQualityChangeFingerprint.kt
  src/main/kotlin/app/revanced/patches/youtube/misc/quality/patch/DefaultVideoQualityPatch.kt
Labels: feature-request

#137 feat: add `custom-video-buffer` patch
  src/main/kotlin/app/revanced/patches/youtube/misc/videobuffer/annotations/CustomVideoBufferCompatibility.kt
  src/main/kotlin/app/revanced/patches/youtube/misc/videobuffer/fingerprints/MaxBufferFingerprint.kt
  src/main/kotlin/app/revanced/patches/youtube/misc/videobuffer/fingerprints/PlaybackBufferFingerprint.kt
  src/main/kotlin/app/revanced/patches/youtube/misc/videobuffer/fingerprints/ReBufferFingerprint.kt
  src/main/kotlin/app/revanced/patches/youtube/misc/videobuffer/patch/CustomVideoBufferPatch.kt
Labels: feature-request
